name: Example workflow for Node using Snyk
on: push
jobs:
  security:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@master
      # snyk test
      - name: Run Snyk monitor to check for vulnerabilities
        continue-on-error: true 
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high --all-projects --target-name=JosanaDH/juice-shop
          command: monitor
      # iac    
      - name: Run Snyk iac report to check for vulnerabilities
        continue-on-error: true 
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high --report --target-name=JosanaDH/juice-shop
          command: iac test
          
      # githuboutput
      - name: SNYK CODE
        uses: snyk/actions/setup@master
        continue-on-error: false
        run: |
          snyk code test --severity-threshold=medium --json-file-output=snyk-report.json
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        
